### ISSUE TITLE
explaining functionality

### ISSUE THREAD

**Issue by juan1978** [MakuraYami/derplib#14]
hello!

im struggling to bring the derplib module to work for the following purpose:

i want to programmatically be able to add an user account (especially username) and programatically login with it (-> single site login)

i tried the same approach as your example-file:

<code>
    var DerpLib = require('./derplib')

```
DerpLib.addAccount('admin', 'root');
console.log('[DB] Loading...');
var db = DerpLib.MM.plugin.load('database').setOrder(1).done(function(){
console.log('[BOT] Starting.');
var permissions = DerpLib.MM.plugin.load('permissions').setOrder(2);
var commands = DerpLib.MM.plugin.load('commands').setOrder(3).autoLoad();
permissions.addRole('user', {access: 1});
permissions.setDefaultRole('user');
// Join a room here - after it's joined use join and leave commands
if(!DerpLib.getRoom('exampleroom'))
new DerpLib.Room({room: 'exampleroom', account: 'admin'});
});
DerpLib.events.on("request", function(req){
console.log('['+req.room.name+']['+req.user.name+'] '+req.message.text);
});
DerpLib.events.on('messageDeleted', function(message, room){
console.log('['+room.name+'][DELETED]['+message.name+']', message.text);
});
```

</code>

... and this is my console output:

<code>
[DB] Loading...
ERROR No data found to load
ERROR No data found to unzip
[DB] Loaded
[DB] Files to load:  []
[BOT] Starting.
[SOCKET] connecting to s64.chatango.com:443
[2014-11-04 19:47:42.841] [TRACE] error - domain error: {"domain":{"domain":null,"_events":{},"members":[]},"domainThrown":true}

</code>

please could you try to help me out with this?

thank you!

**Comment by MakuraYami** [comment]
Pretty late reply but please message me on chatango if you are still looking for help, under the username "barrykun". Thanks!
