### ISSUE TITLE
problem with end_fw

### ISSUE THREAD

**Issue by belldandu** [MakuraYami/derplib#7]
it never comes up owo so the bot is always locked

**Comment by MakuraYami** [comment]
Meh that's annoying. I really don't have time to get into it now, I'll be
working on the lib again in a month or so.

**Comment by belldandu** [comment]
mkay i guess ill make a temporary fix then 
how bout a timeout that after 10 seconds the writelock is set to false?

**Comment by MakuraYami** [comment]
I need to talk to you

**Comment by belldandu** [comment]
sure any time :D
